// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Potres.Dal.Model
{
    public partial class UserImage
    {
        public int UserId { get; set; }
        public byte[] Image { get; set; }

        public virtual User User { get; set; }
    }
}